//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;



/// <summary>
///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
/// </summary>
// Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
// à l'aide d'un outil, tel que ResGen ou Visual Studio.
// Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
// avec l'option /str ou régénérez votre projet VS.
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
internal class Strings {
    
    private static global::System.Resources.ResourceManager resourceMan;
    
    private static global::System.Globalization.CultureInfo resourceCulture;
    
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal Strings() {
    }
    
    /// <summary>
    ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Resources.ResourceManager ResourceManager {
        get {
            if (object.ReferenceEquals(resourceMan, null)) {
                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Strings", typeof(Strings).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }
    
    /// <summary>
    ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
    ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Globalization.CultureInfo Culture {
        get {
            return resourceCulture;
        }
        set {
            resourceCulture = value;
        }
    }
    
    /// <summary>
    ///   Recherche une chaîne localisée semblable à The destination is too small to hold the encoded value..
    /// </summary>
    internal static string Argument_EncodeDestinationTooSmall {
        get {
            return ResourceManager.GetString("Argument_EncodeDestinationTooSmall", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Recherche une chaîne localisée semblable à The OID value was invalid..
    /// </summary>
    internal static string Argument_InvalidOidValue {
        get {
            return ResourceManager.GetString("Argument_InvalidOidValue", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Recherche une chaîne localisée semblable à ASN.1 Enumerated values only apply to enum types without the [Flags] attribute..
    /// </summary>
    internal static string Cryptography_Asn_EnumeratedValueRequiresNonFlagsEnum {
        get {
            return ResourceManager.GetString("Cryptography_Asn_EnumeratedValueRequiresNonFlagsEnum", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Recherche une chaîne localisée semblable à Named bit list operations require an enum with the [Flags] attribute..
    /// </summary>
    internal static string Cryptography_Asn_NamedBitListRequiresFlagsEnum {
        get {
            return ResourceManager.GetString("Cryptography_Asn_NamedBitListRequiresFlagsEnum", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Recherche une chaîne localisée semblable à The encoded named bit list value is larger than the value size of the &apos;{0}&apos; enum..
    /// </summary>
    internal static string Cryptography_Asn_NamedBitListValueTooBig {
        get {
            return ResourceManager.GetString("Cryptography_Asn_NamedBitListValueTooBig", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Recherche une chaîne localisée semblable à Tags with TagClass Universal must have the appropriate TagValue value for the data type being read or written..
    /// </summary>
    internal static string Cryptography_Asn_UniversalValueIsFixed {
        get {
            return ResourceManager.GetString("Cryptography_Asn_UniversalValueIsFixed", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Recherche une chaîne localisée semblable à Unused bit count must be between 0 and 7, inclusive..
    /// </summary>
    internal static string Cryptography_Asn_UnusedBitCountRange {
        get {
            return ResourceManager.GetString("Cryptography_Asn_UnusedBitCountRange", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Recherche une chaîne localisée semblable à Encode cannot be called while a Sequence or SetOf is still open..
    /// </summary>
    internal static string Cryptography_AsnWriter_EncodeUnbalancedStack {
        get {
            return ResourceManager.GetString("Cryptography_AsnWriter_EncodeUnbalancedStack", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Recherche une chaîne localisée semblable à Cannot pop the requested tag as it is not currently in progress..
    /// </summary>
    internal static string Cryptography_AsnWriter_PopWrongTag {
        get {
            return ResourceManager.GetString("Cryptography_AsnWriter_PopWrongTag", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Recherche une chaîne localisée semblable à ASN1 corrupted data..
    /// </summary>
    internal static string Cryptography_Der_Invalid_Encoding {
        get {
            return ResourceManager.GetString("Cryptography_Der_Invalid_Encoding", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Recherche une chaîne localisée semblable à The input to WriteEncodedValue must represent a single encoded value with no trailing data..
    /// </summary>
    internal static string Cryptography_WriteEncodedValue_OneValueAtATime {
        get {
            return ResourceManager.GetString("Cryptography_WriteEncodedValue_OneValueAtATime", resourceCulture);
        }
    }
}
